### ISSUE TITLE
Update TEI Schema

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-process#3]
Could you please update the TEI Schema and add in `<institution></institution>`

` <msDesc>
  <repository>State Collections of Lower Austria</repository>
  <collection>Stella Musulin (Depot)</collection>
  <idno>1, 8</idno>
 </msIdentifier>`

**Comment by linxOD** [comment]
9a0da9c6702a24912f3cd8427e7788bba83d977c
